// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp, defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/search-vault.ts
import { createClient } from "npm:@supabase/supabase-js@2.104.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function sbAnon() {
  const url = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_URL") : process.env.SUPABASE_URL;
  const key = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_ANON_KEY") : process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_vault_default = defineTool({
  name: "search_vault",
  title: "Search vault notes",
  description: "Full-text search across the user's research vault (tickers, themes, layers). Returns matching notes with a snippet and rank.",
  inputSchema: {
    query: z.string().min(1).describe("Search query, e.g. 'NVDA moat' or 'AI infrastructure'."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const sb = sbAnon();
    const { data, error } = await sb.rpc("vault_search", { q: query, lim: limit ?? 10 });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-vault-note.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.104.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sbAnon2() {
  const url = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_URL") : process.env.SUPABASE_URL;
  const key = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_ANON_KEY") : process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient2(url, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_vault_note_default = defineTool2({
  name: "get_vault_note",
  title: "Get vault note",
  description: "Fetch a single research vault note by type (ticker/theme/layer/etc.) and identifier. Returns full body and sections.",
  inputSchema: {
    type: z2.string().min(1).describe("Note type, e.g. 'ticker', 'theme', 'layer'."),
    identifier: z2.string().min(1).describe("Identifier within that type, e.g. 'NVDA'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, identifier }) => {
    const sb = sbAnon2();
    const { data, error } = await sb.from("vault_notes_meta").select("type,identifier,body,body_sections,updated_at").eq("type", type.toLowerCase()).eq("identifier", identifier.toLowerCase()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Note not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/tools/list-scores.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@2.104.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sbAnon3() {
  const url = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_URL") : process.env.SUPABASE_URL;
  const key = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_ANON_KEY") : process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient3(url, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_scores_default = defineTool3({
  name: "list_scores",
  title: "List latest scores snapshot",
  description: "Return the latest snapshot of 6D scores across holdings and watchlist. Optionally filter by ticker.",
  inputSchema: {
    ticker: z3.string().optional().describe("Optional ticker to filter, e.g. 'NVDA'."),
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ ticker, limit }) => {
    const sb = sbAnon3();
    let q = sb.from("scores_snapshot").select("*").limit(limit ?? 50);
    if (ticker) q = q.ilike("ticker", ticker);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "eervjywaxpxqdjjhtguz";
var pingTool = defineTool4({
  name: "ping",
  title: "Ping",
  description: "Health check. Returns pong.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    return {
      content: [{ type: "text", text: "pong" }]
    };
  }
});
var mcp_default = defineMcp({
  name: "stellar-command-mcp",
  title: "Stellar Command MCP",
  version: "0.3.0",
  instructions: "Tools for the Stellar Command dashboard. Use `search_vault` to full-text search research notes, `get_vault_note` to fetch a single note's full body, and `list_scores` to inspect the latest 6D scores snapshot.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [pingTool, search_vault_default, get_vault_note_default, list_scores_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
